version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = [
    "assets/**",
    "build.assets/**",
    "docker/**",
    "docs/**",
    "examples/**",
    "fixtures/**",
    "vagrant/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/gravitational/teleport"
  dependencies_vendored = true
  build_tags = ["fips", "pam", "bpf"]
